# -*- coding: utf-8 -*-
"""
Summarize energy fitting errors from triple-axis plot outputs.

Input is the `triple_axis_plot_summary.csv` generated by
`plot_triple_axis_all_runs.py`. The script writes compact CSV tables and, when
openpyxl is available, one Excel workbook with the same summaries.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SUMMARY_CSV = (
    PROJECT_ROOT
    / "output"
    / "models"
    / "nn_results_residual_v2"
    / "triple_axis_all_runs_first5"
    / "triple_axis_plot_summary.csv"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build average error tables from triple_axis_plot_summary.csv."
    )
    parser.add_argument(
        "--summary-csv",
        default=str(DEFAULT_SUMMARY_CSV),
        help="Path to triple_axis_plot_summary.csv.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory. Default: same folder as --summary-csv.",
    )
    parser.add_argument(
        "--normal-label",
        type=int,
        default=0,
        help="Curve quality label treated as normal for the filtered summary.",
    )
    return parser.parse_args()


def resolve_path(path: str | Path) -> Path:
    path = Path(path)
    if path.is_absolute():
        return path
    return PROJECT_ROOT / path


def ensure_error_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    for col in ["real_energy_wh", "fusion_energy_wh", "fusion_error_pct", "run_class", "quality_label"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    if "fusion_error_pct" not in df.columns or df["fusion_error_pct"].isna().all():
        if {"real_energy_wh", "fusion_energy_wh"}.issubset(df.columns):
            real = df["real_energy_wh"]
            fusion = df["fusion_energy_wh"]
            df["fusion_error_pct"] = np.where(real.abs() > 1e-9, (fusion - real) / real * 100.0, np.nan)
        else:
            raise KeyError("Need fusion_error_pct, or both real_energy_wh and fusion_energy_wh.")

    df["abs_error_pct"] = df["fusion_error_pct"].abs()
    df["squared_error_pct"] = df["fusion_error_pct"] ** 2
    df["energy_error_wh"] = df["fusion_energy_wh"] - df["real_energy_wh"]
    return df


def build_summary(df: pd.DataFrame, group_cols: list[str] | None = None) -> pd.DataFrame:
    group_cols = group_cols or []
    valid = df.dropna(subset=["fusion_error_pct", "real_energy_wh", "fusion_energy_wh"]).copy()
    valid = valid[valid["real_energy_wh"].abs() > 1e-9]

    if group_cols:
        grouped = valid.groupby(group_cols, dropna=False)
    else:
        valid = valid.assign(scope="全部")
        group_cols = ["scope"]
        grouped = valid.groupby(group_cols, dropna=False)

    rows = []
    for key, group in grouped:
        if not isinstance(key, tuple):
            key = (key,)
        real_total = float(group["real_energy_wh"].sum())
        fusion_total = float(group["fusion_energy_wh"].sum())
        weighted_error_pct = (fusion_total - real_total) / real_total * 100.0 if abs(real_total) > 1e-9 else np.nan
        row = {col: value for col, value in zip(group_cols, key)}
        row.update(
            {
                "趟次数": int(len(group)),
                "平均误差%": float(group["fusion_error_pct"].mean()),
                "平均绝对误差%": float(group["abs_error_pct"].mean()),
                "中位绝对误差%": float(group["abs_error_pct"].median()),
                "RMSE误差%": float(np.sqrt(group["squared_error_pct"].mean())),
                "能耗加权误差%": float(weighted_error_pct),
                "真实能耗合计Wh": real_total,
                "融合能耗合计Wh": fusion_total,
                "能耗差合计Wh": float(group["energy_error_wh"].sum()),
            }
        )
        rows.append(row)

    result = pd.DataFrame(rows)
    metric_cols = [
        "平均误差%",
        "平均绝对误差%",
        "中位绝对误差%",
        "RMSE误差%",
        "能耗加权误差%",
        "真实能耗合计Wh",
        "融合能耗合计Wh",
        "能耗差合计Wh",
    ]
    for col in metric_cols:
        if col in result.columns:
            result[col] = result[col].round(3)
    return result.sort_values(group_cols).reset_index(drop=True)


def write_outputs(output_dir: Path, tables: dict[str, pd.DataFrame]) -> Path | None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, table in tables.items():
        table.to_csv(output_dir / f"{name}.csv", index=False, encoding="utf-8-sig")

    xlsx_path = output_dir / "triple_axis_error_summary.xlsx"
    try:
        with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
            for name, table in tables.items():
                sheet_name = name[:31]
                table.to_excel(writer, sheet_name=sheet_name, index=False)

            wb = writer.book
            for ws in wb.worksheets:
                ws.freeze_panes = "A2"
                for column_cells in ws.columns:
                    header = str(column_cells[0].value or "")
                    max_len = max([len(str(cell.value or "")) for cell in column_cells[:200]] + [len(header)])
                    ws.column_dimensions[column_cells[0].column_letter].width = min(max(max_len + 2, 10), 36)
        return xlsx_path
    except Exception as exc:
        print(f"Excel 汇总写入失败，仅保留 CSV。原因: {exc}")
        return None


def main() -> int:
    args = parse_args()
    summary_csv = resolve_path(args.summary_csv)
    output_dir = resolve_path(args.output_dir) if args.output_dir else summary_csv.parent

    if not summary_csv.exists():
        raise FileNotFoundError(f"找不到输入文件: {summary_csv}")

    df = pd.read_csv(summary_csv)
    df = ensure_error_columns(df)

    normal_df = df[df["quality_label"] == args.normal_label].copy() if "quality_label" in df.columns else df.copy()

    tables = {
        "总体平均误差": build_summary(df),
        "质量正常平均误差": build_summary(normal_df),
        "按区间平均误差": build_summary(df, ["section"]),
        "按区间_质量正常平均误差": build_summary(normal_df, ["section"]),
        "按区间等级平均误差": build_summary(df, ["section", "run_class"]),
        "按区间等级_质量正常平均误差": build_summary(normal_df, ["section", "run_class"]),
    }

    xlsx_path = write_outputs(output_dir, tables)

    overall = tables["总体平均误差"].iloc[0]
    normal = tables["质量正常平均误差"].iloc[0]
    print(f"输入明细: {summary_csv}")
    print(f"输出目录: {output_dir}")
    print(
        "全部趟次: "
        f"n={overall['趟次数']}, 平均误差={overall['平均误差%']}%, "
        f"平均绝对误差={overall['平均绝对误差%']}%, 加权误差={overall['能耗加权误差%']}%"
    )
    print(
        "质量正常: "
        f"n={normal['趟次数']}, 平均误差={normal['平均误差%']}%, "
        f"平均绝对误差={normal['平均绝对误差%']}%, 加权误差={normal['能耗加权误差%']}%"
    )
    if xlsx_path:
        print(f"Excel 汇总: {xlsx_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
