from __future__ import annotations

import argparse
import csv
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


DEFAULT_STATION_MAP = Path(r"D:\energy_conservation\opentrack_timetables\station_id_mapping.csv")
DEFAULT_LOG_DIR = Path(r"D:\energy_conservation\opentrack_otd_logs")
DEFAULT_OUTPUT_DIR = Path(r"D:\energy_conservation\output\opentrack_route_map")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a station-section to OpenTrack routeID/offset map from OTD JSONL logs. "
            "If trainPositionReport messages are available, route offsets are taken from "
            "them. Otherwise the script falls back to routeEntry messages and writes a "
            "routeID-only map."
        )
    )
    parser.add_argument(
        "--log",
        default=str(DEFAULT_LOG_DIR),
        help="A JSONL log file, or a directory containing otd_messages_*.jsonl. Latest file is used.",
    )
    parser.add_argument(
        "--station-map",
        default=str(DEFAULT_STATION_MAP),
        help="station_id_mapping.csv generated by make_opentrack_timetables.py.",
    )
    parser.add_argument(
        "--course-id",
        default=None,
        help="Course ID in station_id_mapping.csv. Defaults to --train-id if present, otherwise first course.",
    )
    parser.add_argument(
        "--train-id",
        default=None,
        help="Train/course ID to analyze. If omitted, infer the most common trainID in position reports.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Directory for generated CSV files.",
    )
    parser.add_argument(
        "--prefix",
        default="opentrack_probe",
        help="Output file prefix.",
    )
    return parser.parse_args()


def resolve_log_path(path_text: str) -> Path:
    path = Path(path_text)
    if path.is_file():
        return path
    if path.is_dir():
        files = sorted(path.glob("otd_messages_*.jsonl"), key=lambda p: p.stat().st_mtime)
        if files:
            return files[-1]
        files = sorted(path.glob("*.jsonl"), key=lambda p: p.stat().st_mtime)
        if files:
            return files[-1]
    raise FileNotFoundError(f"No JSONL OTD log found: {path}")


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_no} is not valid JSON: {exc}") from exc
    return rows


def read_station_sequence(path: Path, course_id: str | None, train_id: str | None) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"{path} is empty.")

    available = [row.get("course_id", "") for row in rows]
    target_course = course_id or train_id
    if target_course and target_course in set(available):
        filtered = [row for row in rows if row.get("course_id") == target_course]
    else:
        first_course = rows[0].get("course_id", "")
        filtered = [row for row in rows if row.get("course_id") == first_course]

    seen: set[str] = set()
    sequence: list[dict[str, str]] = []
    for row in filtered:
        station_id = (row.get("station_id") or "").strip()
        if not station_id or station_id in seen:
            continue
        seen.add(station_id)
        sequence.append(
            {
                "station_id": station_id,
                "station_name": (row.get("station_name") or "").strip(),
                "course_id": (row.get("course_id") or "").strip(),
            }
        )
    if len(sequence) < 2:
        raise ValueError(f"Need at least two stations in {path}.")
    return sequence


def as_float(value: Any) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def infer_train_id(records: list[dict[str, Any]], requested: str | None) -> str:
    if requested:
        return requested
    counts: Counter[str] = Counter()
    for rec in records:
        attrs = rec.get("attrs") or {}
        if rec.get("message") in {
            "trainPositionReport",
            "routeEntry",
            "trainArrival",
            "trainDeparture",
            "trainPass",
        } and attrs.get("trainID"):
            counts[str(attrs["trainID"])] += 1
    if not counts:
        raise ValueError("No train-related OTD messages found and --train-id was not provided.")
    train_id, _ = counts.most_common(1)[0]
    return train_id


def collect_records(records: list[dict[str, Any]], train_id: str):
    positions: list[dict[str, Any]] = []
    events: list[dict[str, Any]] = []
    for rec in records:
        message = rec.get("message")
        attrs = rec.get("attrs") or {}
        if attrs.get("trainID") != train_id:
            continue
        if message == "trainPositionReport":
            time = as_float(attrs.get("time"))
            route_offset = as_float(attrs.get("routeOffset"))
            if time is None:
                continue
            positions.append(
                {
                    "message": message,
                    "trainID": train_id,
                    "time": time,
                    "routeID": attrs.get("routeID", ""),
                    "routeOffset": route_offset,
                    "delay": as_float(attrs.get("delay")),
                    "speed": as_float(attrs.get("speed")),
                    "acceleration": as_float(attrs.get("acceleration")),
                    "received_at": rec.get("received_at", ""),
                }
            )
        elif message in {"trainArrival", "trainDeparture", "trainPass"}:
            time = as_float(attrs.get("time"))
            if time is None:
                continue
            events.append(
                {
                    "message": message,
                    "trainID": train_id,
                    "stationID": attrs.get("stationID", ""),
                    "time": time,
                    "delay": as_float(attrs.get("delay")),
                    "received_at": rec.get("received_at", ""),
                }
            )
    positions.sort(key=lambda row: row["time"])
    events.sort(key=lambda row: row["time"])
    return positions, events


def collect_route_entries(records: list[dict[str, Any]], train_id: str) -> list[dict[str, Any]]:
    route_entries: list[dict[str, Any]] = []
    for rec in records:
        if rec.get("message") != "routeEntry":
            continue
        attrs = rec.get("attrs") or {}
        if attrs.get("trainID") != train_id:
            continue
        time = as_float(attrs.get("time"))
        route_id = attrs.get("routeID", "")
        if time is None or not route_id:
            continue
        route_entries.append(
            {
                "message": "routeEntry",
                "trainID": train_id,
                "time": time,
                "routeID": route_id,
                "received_at": rec.get("received_at", ""),
            }
        )
    route_entries.sort(key=lambda row: row["time"])
    return route_entries


def event_index(events: list[dict[str, Any]]):
    by_station: dict[str, dict[str, list[dict[str, Any]]]] = defaultdict(lambda: defaultdict(list))
    for event in events:
        by_station[event["stationID"]][event["message"]].append(event)
    return by_station


def first_event_after(events: list[dict[str, Any]], threshold: float | None = None) -> dict[str, Any] | None:
    if threshold is None:
        return events[0] if events else None
    for event in events:
        if event["time"] >= threshold:
            return event
    return None


def start_event_for_station(by_station, station_id: str) -> dict[str, Any] | None:
    candidates: list[dict[str, Any]] = []
    for message in ("trainDeparture", "trainPass", "trainArrival"):
        candidates.extend(by_station.get(station_id, {}).get(message, []))
    return min(candidates, key=lambda row: row["time"]) if candidates else None


def end_event_for_station(by_station, station_id: str, after_time: float | None) -> dict[str, Any] | None:
    for message in ("trainArrival", "trainPass", "trainDeparture"):
        event = first_event_after(by_station.get(station_id, {}).get(message, []), after_time)
        if event:
            return event
    return None


def unique_route_sequence(positions: list[dict[str, Any]]) -> str:
    sequence: list[str] = []
    last_route = None
    for pos in positions:
        route = pos.get("routeID") or ""
        if route and route != last_route:
            sequence.append(route)
            last_route = route
    return " | ".join(sequence)


def unique_route_entries(route_entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Keep the first chronological entry for each routeID.

    The listener log can contain several simulation runs appended to the same file.
    For the route-only fallback, a single chronological route sequence is enough.
    """

    seen: set[str] = set()
    unique: list[dict[str, Any]] = []
    for entry in route_entries:
        route_id = entry.get("routeID") or ""
        if not route_id or route_id in seen:
            continue
        seen.add(route_id)
        unique.append(entry)
    return unique


def build_route_map(
    station_sequence: list[dict[str, str]],
    positions: list[dict[str, Any]],
    events: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    by_station = event_index(events)
    rows: list[dict[str, Any]] = []

    for i in range(len(station_sequence) - 1):
        start_station = station_sequence[i]
        end_station = station_sequence[i + 1]
        start_event = start_event_for_station(by_station, start_station["station_id"])
        end_event = end_event_for_station(
            by_station,
            end_station["station_id"],
            start_event["time"] if start_event else None,
        )

        warnings: list[str] = []
        if start_event is None:
            warnings.append("missing_start_station_event")
            start_time = None
        else:
            start_time = start_event["time"]

        if end_event is None:
            warnings.append("missing_end_station_event")
            end_time = None
        else:
            end_time = end_event["time"]

        if start_time is None or end_time is None:
            section_positions: list[dict[str, Any]] = []
        else:
            section_positions = [
                pos for pos in positions if start_time <= pos["time"] <= end_time
            ]
        if not section_positions:
            warnings.append("no_position_reports_in_section")

        first_pos = section_positions[0] if section_positions else {}
        last_pos = section_positions[-1] if section_positions else {}
        rows.append(
            {
                "section_index": i + 1,
                "section": f"{start_station['station_name']}-{end_station['station_name']}",
                "start_station_id": start_station["station_id"],
                "start_station_name": start_station["station_name"],
                "end_station_id": end_station["station_id"],
                "end_station_name": end_station["station_name"],
                "start_event_type": start_event["message"] if start_event else "",
                "start_event_time": start_time,
                "end_event_type": end_event["message"] if end_event else "",
                "end_event_time": end_time,
                "startRouteID": first_pos.get("routeID", ""),
                "startRouteOffset": first_pos.get("routeOffset"),
                "endRouteID": last_pos.get("routeID", ""),
                "endRouteOffset": last_pos.get("routeOffset"),
                "first_report_time": first_pos.get("time"),
                "last_report_time": last_pos.get("time"),
                "report_count": len(section_positions),
                "route_sequence": unique_route_sequence(section_positions),
                "warning": ";".join(warnings),
            }
        )
    return rows


def build_route_map_from_route_entries(
    station_sequence: list[dict[str, str]],
    events: list[dict[str, Any]],
    route_entries: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Build a usable routeID map when OpenTrack did not emit position reports.

    This fallback is less precise because route offsets are unavailable. For each
    section it maps the start to the current route at offset 0. When possible, it
    maps the end to the next route at offset 0, which is usually the beginning of
    the following station section.
    """

    by_station = event_index(events)
    unique_routes = unique_route_entries(route_entries)
    rows: list[dict[str, Any]] = []

    for i in range(len(station_sequence) - 1):
        start_station = station_sequence[i]
        end_station = station_sequence[i + 1]
        start_event = start_event_for_station(by_station, start_station["station_id"])
        end_event = end_event_for_station(
            by_station,
            end_station["station_id"],
            start_event["time"] if start_event else None,
        )

        current_route = unique_routes[i] if i < len(unique_routes) else {}
        next_route = unique_routes[i + 1] if i + 1 < len(unique_routes) else {}
        warnings = ["fallback_route_entry_no_position_reports"]
        if not current_route:
            warnings.append("missing_route_entry_for_section")
        if not next_route:
            warnings.append("missing_next_route_entry_for_end_offset")

        rows.append(
            {
                "section_index": i + 1,
                "section": f"{start_station['station_name']}-{end_station['station_name']}",
                "start_station_id": start_station["station_id"],
                "start_station_name": start_station["station_name"],
                "end_station_id": end_station["station_id"],
                "end_station_name": end_station["station_name"],
                "start_event_type": start_event["message"] if start_event else "",
                "start_event_time": start_event["time"] if start_event else None,
                "end_event_type": end_event["message"] if end_event else "",
                "end_event_time": end_event["time"] if end_event else None,
                "startRouteID": current_route.get("routeID", ""),
                "startRouteOffset": 0.0 if current_route else None,
                "endRouteID": next_route.get("routeID", current_route.get("routeID", "")),
                "endRouteOffset": 0.0 if next_route else None,
                "first_report_time": None,
                "last_report_time": None,
                "report_count": 0,
                "route_sequence": current_route.get("routeID", ""),
                "warning": ";".join(warnings),
            }
        )
    return rows


def write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str] | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        keys: list[str] = []
        for row in rows:
            for key in row:
                if key not in keys:
                    keys.append(key)
        fieldnames = keys
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    args = parse_args()
    log_path = resolve_log_path(args.log)
    records = read_jsonl(log_path)
    train_id = infer_train_id(records, args.train_id)
    stations = read_station_sequence(Path(args.station_map), args.course_id, train_id)
    positions, events = collect_records(records, train_id)
    route_entries = collect_route_entries(records, train_id)

    if not events:
        raise ValueError(f"No trainArrival/trainDeparture/trainPass messages found for trainID={train_id!r}.")

    if positions:
        route_rows = build_route_map(stations, positions, events)
        map_mode = "position_reports"
    elif route_entries:
        route_rows = build_route_map_from_route_entries(stations, events, route_entries)
        map_mode = "route_entry_fallback"
    else:
        raise ValueError(
            f"No trainPositionReport or routeEntry messages found for trainID={train_id!r}."
        )
    output_dir = Path(args.output_dir)
    route_path = output_dir / f"{args.prefix}_route_map.csv"
    pos_path = output_dir / f"{args.prefix}_position_reports.csv"
    events_path = output_dir / f"{args.prefix}_station_events.csv"
    route_entries_path = output_dir / f"{args.prefix}_route_entries.csv"

    write_csv(route_path, route_rows)
    write_csv(pos_path, positions)
    write_csv(events_path, events)
    write_csv(route_entries_path, route_entries)

    warnings = sum(1 for row in route_rows if row.get("warning"))
    print(f"Log: {log_path}")
    print(f"Train ID: {train_id}")
    print(f"Map mode: {map_mode}")
    print(f"Stations: {len(stations)}, sections: {len(route_rows)}")
    print(
        f"Position reports: {len(positions)}, route entries: {len(route_entries)}, "
        f"station events: {len(events)}"
    )
    print(f"Route map: {route_path}")
    print(f"Position report table: {pos_path}")
    print(f"Station event table: {events_path}")
    print(f"Route entry table: {route_entries_path}")
    if warnings:
        print(f"Warnings: {warnings} section(s) need review. See warning column.")
    else:
        print("Warnings: none")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
